version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    hostname: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
        
    depends_on:
      - zipkin
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=toilet
      - POSTGRES_USER=toilet
      - POSTGRES_DB=toilet
    ports:
      - "5432:5432"