receivers:
  otlp:
    protocols:
         grpc:

exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  logging:
    verbosity: detailed


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
