
### Capture the response body ID
@customerId = e7b4fdec-1a5a-4077-b1b2-67befd54bf13

### POST Create PAID Toilet
POST http://localhost:8081/toilet
Content-Type: application/json

{
  "name": "Paid",
  "latitude": 37.7749,
  "longitude": -166.4194,
  "price": 200,
  "customerId": "{{customerId}}"
}

### POST Create FREE Toilet
POST http://localhost:8081/toilet
Content-Type: application/json

{
  "name": "My Toilet",
  "latitude": 0.7749,
  "longitude": 0.4194,
  "price": 0,
  "customerId": "{{customerId}}"
}

