--CREATE TYPE TOILET_TYPE AS ENUM ('FREE', 'PAID');
CREATE TABLE TOILETS (
    ID          UUID            NOT NULL PRIMARY KEY,
    NAME        VARCHAR(100)    NOT NULL,
    PRICE       INTEGER         NOT NULL,
    TYPE        VARCHAR(100)    NOT NULL,
    VERSION     INT             NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP       DEFAULT NOW()
);

CREATE TABLE TOILET_GEOLOCATION (
    TOILET_ID   UUID            NOT NULL PRIMARY KEY,
    LATITUDE    DECIMAL(9,6)    NOT NULL,
    LONGITUDE   DECIMAL(9,6)    NOT NULL,
    VERSION     INT             NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP       DEFAULT NOW(),
    FOREIGN KEY (TOILET_ID) REFERENCES TOILETS(ID)
);
